"""add table materiales, registro_proceso_ejecutado, procesos_ejecutados

Revision ID: 455d0fe07ad6
Revises: 86ebce48b8ce
Create Date: 2024-10-21 01:10:47.029970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455d0fe07ad6'
down_revision: Union[str, None] = '86ebce48b8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiales',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_entrada', sa.BigInteger(), nullable=False),
    sa.Column('cantidad_entrada', sa.Float(), nullable=True),
    sa.Column('cantidad_salida', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrada'], ['entradas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procesos_ejecutados',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_proceso', sa.BigInteger(), nullable=False),
    sa.Column('no_conformidades', sa.Integer(), nullable=True),
    sa.Column('conformidades', sa.Integer(), nullable=True),
    sa.Column('num_etapas_con_conformidades', sa.Integer(), nullable=True),
    sa.Column('tasa_de_exito', sa.Float(), nullable=True),
    sa.Column('cantidad_salida', sa.Float(), nullable=True),
    sa.Column('cantidad_entrada', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_proceso'], ['procesos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_proceso_ejecutado',
    sa.Column('id_proceso_ejecutado', sa.BigInteger(), nullable=False),
    sa.Column('id_registro', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_proceso_ejecutado'], ['procesos_ejecutados.id'], ),
    sa.ForeignKeyConstraint(['id_registro'], ['registro.id'], ),
    sa.PrimaryKeyConstraint('id_proceso_ejecutado', 'id_registro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_proceso_ejecutado')
    op.drop_table('procesos_ejecutados')
    op.drop_table('materiales')
    # ### end Alembic commands ###
