"""material add field usos for counting use of them

Revision ID: 7609fd6a0cce
Revises: 99bcd3cfb05f
Create Date: 2024-10-22 09:36:17.515030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7609fd6a0cce'
down_revision: Union[str, None] = '99bcd3cfb05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materiales', sa.Column('usos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materiales', 'usos')
    # ### end Alembic commands ###
