"""modify int to float material table

Revision ID: 99bcd3cfb05f
Revises: 455d0fe07ad6
Create Date: 2024-10-22 02:18:45.709185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99bcd3cfb05f'
down_revision: Union[str, None] = '455d0fe07ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
